name: CI Pipeline

on:
  push:
    branches:
      - development
      - main

env:
  PYTHON_VERSION: "3.11.14"
  APP_PATH: "backend"
  GITOPS_REPOSITORY: "nurielb/final-project-helm.git"
  DOCKER_IMAGE_TAG: ""
  IS_PROD: ""
  BRANCH_MAP: >
    {"main":"values-prod.yaml",
    "development":"values-dev.yaml"}

jobs:
  build:
    runs-on: ${{ vars.FINAL_PROJECT_BASE_IMAGE }}
    steps:

      - 
        name: Checkout repository branch
        uses: actions/checkout@v6
        with:
          fetch-depth: 10

      - 
        name: Set variables
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          BRANCH=${GITHUB_REF_NAME}

          if [ "$BRANCH" = "main" ]; then
            echo "DOCKER_IMAGE_TAG=prod-$SHORT_SHA" >> $GITHUB_ENV
            echo "IS_PROD=true" >> $GITHUB_ENV
          else
            echo "DOCKER_IMAGE_TAG=$BRANCH-$SHORT_SHA" >> $GITHUB_ENV
            echo "IS_PROD=false" >> $GITHUB_ENV
          fi

      -
        name: Display variables
        run: |
          echo "BASE_IMAGE: ${{ vars.FINAL_PROJECT_BASE_IMAGE }}"
          echo "PYTHON_VERSION: ${{ env.PYTHON_VERSION }}"
          echo "APP_PATH: ${{ env.APP_PATH }}"
          echo "DOCKER_IMAGE_TAG: ${{ env.DOCKER_IMAGE_TAG }}"

      - 
        name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      -
        name: Install dependencies
        run: pip install -r "${{ env.APP_PATH }}/requirements.txt"

      -
        name: Run test
        run: pytest "${{ env.APP_PATH }}"

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Build and Push image
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.APP_PATH }}
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/final-project-backend:${{ env.DOCKER_IMAGE_TAG }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha,scope=${{ runner.os }}-buildx
          cache-to: type=gha,scope=${{ runner.os }}-buildx-new,mode=max

      - 
        name: Set values file
        run: echo "VALUES_FILE=${{ fromJson(env.BRANCH_MAP)[github.ref_name]] }}" >> $GITHUB_ENV

      - 
        name: Checkout repository branch
        uses: actions/checkout@v6
        with:
          repository: ${{ env.GITOPS_REPOSITORY }}
          ref: main
          fetch-depth: 10

      -
        name: Update GitOps Repository
        run: |
          values_file_path="./charts/final_project/values-${GITHUB_REF_NAME}.yaml"
          yq -i '.container.image.tag = "${{ env.DOCKER_IMAGE_TAG }}"' ${values_file_path}

      -
        name: Create pull request to main branch
        if: env.IS_PROD == true
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Updated Production image tag
          title: Update Production Image Tag
          body: Updated Production image tag
          branch: production-image-update

      -
        name: Auto Commit
        if: env.IS_PROD == false
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Updated GITHUB_REF_NAME image tag
          tag_name: DOCKER_IMAGE_TAG
          token: ${{ secrets.GITOPS_TOKEN }}